"use client";
import {useState} from "react";
import { ScanStage } from "../../scan-stage";
import { useLiveBatches, usePreferredId } from "../../use-live-batches";
import { useQrFragment } from "../../use-qr-fragment";
import styles from "../../workspace.module.css";
import { formatBatchLabel, type ControlBatch } from "../batch-label";
type Batch=ControlBatch;
export function LoadingControl({batches:initial,siteId}:{batches:Batch[];siteId?:string}){const{batches}=useLiveBatches(initial,["awaiting_cart","in_progress"],siteId);const[batchId,setBatchId]=usePreferredId(batches.map(batch=>batch.id));const{token}=useQrFragment("cart");const[result,setResult]=useState<{kind:string;reasonCode?:string;orderStatus?:string}|null>(null);const[submitting,setSubmitting]=useState(false);const scanResult=result;async function submit(){if(!batchId||!token){setResult({kind:"denied",reasonCode:"invalid_qr"});return}setSubmitting(true);try{const response=await fetch("/api/operations/load-cart",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({batch_id:batchId,qr_token:token,change_request_id:crypto.randomUUID()})});setResult(await response.json())}catch{setResult({kind:"failed",reasonCode:"service_unavailable"})}finally{setSubmitting(false)}}return <div aria-live="polite"><ScanStage scanned={Boolean(token)} waitingText="請掃描來源洗衣車固定 QR。" readyText="已掃描來源車，請確認裝車。"><label>待裝車批次<select value={batchId} onChange={event=>setBatchId(event.target.value)}>{batches.length===0?<option value="">目前沒有可裝車批次</option>:batches.map(batch=><option key={batch.id} value={batch.id}>{formatBatchLabel(batch)}</option>)}</select></label><button type="button" onClick={submit} disabled={!batchId||!token||submitting}>確認裝回來源車</button></ScanStage>{scanResult?.reasonCode?<p className={styles.errorNotice} role="alert">裝車未完成：{scanResult.reasonCode}</p>:scanResult?<p className={styles.successNotice} role="status">裝車完成，洗衣單狀態：{scanResult.orderStatus??"待取件"}。</p>:null}</div>}
