import { afterEach, expect, test } from "vitest";
import { createTestDatabase, type TestDatabase } from "../support/test-database";
let database: TestDatabase | undefined;
afterEach(async()=>{await database?.close();database=undefined;});

test("同一洗衣單可依新增分類建立有序必要批次", async()=>{
  database=await createTestDatabase(); const supervisor="10000000-0000-0000-0000-000000001301"; const profile="40000000-0000-0000-0000-000000001301"; const worker="10000000-0000-0000-0000-000000001302"; const workerProfile="40000000-0000-0000-0000-000000001302"; const ids=Array.from({length:8},(_,i)=>`60000000-0000-0000-0000-0000000013${10+i}`);
  await database.exec(`insert into auth.users(id,email) values('${supervisor}','split.supervisor@example.com'),('${worker}','split.worker@example.com'); insert into public.user_access_profiles(id,email,auth_user_id) values('${profile}','split.supervisor@example.com','${supervisor}'),('${workerProfile}','split.worker@example.com','${worker}'); insert into public.access_memberships(user_access_profile_id,role,operating_site_id) select '${profile}','laundry_supervisor',id from public.operating_sites where code='MAIN'; insert into public.access_memberships(user_access_profile_id,role,operating_site_id) select '${workerProfile}','laundry_worker',id from public.operating_sites where code='MAIN'; insert into public.institutions(code,name,operating_site_id) select 'SPLIT-CARE','拆批機構',id from public.operating_sites where code='MAIN';`);
  await database.query(`select set_config('request.jwt.claim.sub',$1,false)`,[supervisor]); await database.exec("set role authenticated");
  const stage=[{stage_order:1,name:"清洗",standard_minutes:30,equipment_type:"washer",compatibility_conditions:{},transition_mode:"manual",requires_operator_confirmation:true}];
  const soiled=await database.query<{procedure_template_id:string;procedure_version_id:string}>(`select * from public.create_procedure_template_draft(null,$1,$2,$3,$4::jsonb,$5,$6)`,["MAIN","SOILED","拆批汙衣",JSON.stringify(stage),ids[0],"建立汙衣程序"]); await database.query(`select * from public.publish_procedure_template_version($1,$2,$3)`,[soiled.rows[0].procedure_version_id,ids[1],"發布汙衣程序"]);
  const bib=await database.query<{procedure_template_id:string;procedure_version_id:string}>(`select * from public.create_procedure_template_draft(null,$1,$2,$3,$4::jsonb,$5,$6)`,["MAIN","BIB","拆批圍兜",JSON.stringify(stage),ids[2],"建立圍兜程序"]); await database.query(`select * from public.publish_procedure_template_version($1,$2,$3)`,[bib.rows[0].procedure_version_id,ids[3],"發布圍兜程序"]);
  const cart=await database.query<{laundry_cart_id:string}>(`select laundry_cart_id from public.register_laundry_cart($1,$2,$3,$4)`,["SPLIT-CART","SPLIT-CARE",ids[4],"建立拆批車"]); const qr=await database.query<{qr_token:string}>(`select qr_token from public.get_current_laundry_cart_qr($1)`,[cart.rows[0].laundry_cart_id]); await database.exec("set role anon"); await database.query(`select * from public.create_laundry_order_from_cart_qr($1,$2)`,[qr.rows[0].qr_token,ids[5]]);
  await database.query(`select set_config('request.jwt.claim.sub',$1,false)`,[worker]); await database.exec("set role authenticated"); const received=await database.query<{laundry_order_id:string}>(`select laundry_order_id from public.receive_laundry_order_from_cart_qr($1,$2::jsonb,$3)`,[qr.rows[0].qr_token,JSON.stringify(["SOILED"]),ids[6]]);
  const split=await database.query<{batch_count:number;reason_code:string}>(`select batch_count,reason_code from public.split_laundry_order_into_batches($1,$2::jsonb,$3)`,[received.rows[0].laundry_order_id,JSON.stringify(["BIB"]),ids[7]]); const batches=await database.query<{batch_sequence:number;required:boolean}>(`select batch_sequence,required from public.laundry_batches where laundry_order_id=$1::uuid order by batch_sequence`,[received.rows[0].laundry_order_id]);
  expect(split.rows).toEqual([{batch_count:1,reason_code:"split"}]); expect(batches.rows).toEqual([{batch_sequence:1,required:true},{batch_sequence:2,required:true}]);
});
