"use client";
import {useState} from "react";
import { ScanStage } from "../../scan-stage";
import { useLiveBatches, usePreferredId } from "../../use-live-batches";
import { useQrFragment } from "../../use-qr-fragment";
import styles from "../../workspace.module.css";
import { formatBatchLabel, type ControlBatch } from "../batch-label";
type Batch=ControlBatch;
export function DryingControl({batches:initial,siteId,mode="start",focusedBatchId}:{batches:Batch[];siteId?:string;mode?:"start"|"complete";focusedBatchId?:string}){const{batches}=useLiveBatches(initial,mode==="complete"?["in_progress"]:["not_started"],siteId);const visible=focusedBatchId?batches.filter(batch=>batch.id===focusedBatchId):batches;const[batchId,setBatchId]=usePreferredId((visible.length>0?visible:batches).map(batch=>batch.id));const{token}=useQrFragment("equipment");const[result,setResult]=useState<{kind:string;status?:string;reasonCode?:string}|null>(null);const[submitting,setSubmitting]=useState(false);async function submit(path:string){if(!batchId||!token){setResult({kind:"denied",reasonCode:"invalid_qr"});return}setSubmitting(true);try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({batch_id:batchId,qr_token:token,change_request_id:crypto.randomUUID()})});setResult(await response.json())}catch{setResult({kind:"failed",reasonCode:"service_unavailable"})}finally{setSubmitting(false)}}const failed=result?.kind==="invalid"||result?.kind==="denied"||result?.kind==="failed";return <div aria-live="polite"><ScanStage scanned={Boolean(token)} waitingText="請掃描烘衣機固定 QR。" readyText={mode==="complete"?"已帶入執行中單據，確認後結束烘乾。":"已掃描烘衣機，確認後開始烘乾。"}><label>{mode==="complete"?"執行中單據":"待烘乾批次"}<select value={batchId} onChange={event=>setBatchId(event.target.value)} disabled={mode==="complete"}>{visible.length===0?<option value="">{mode==="complete"?"目前沒有這台烘衣機的執行中單據":"目前沒有可烘乾批次"}</option>:visible.map(batch=><option key={batch.id} value={batch.id}>{formatBatchLabel(batch)}</option>)}</select></label>{mode==="complete"?<button type="button" onClick={()=>void submit("/api/operations/complete-stage")} disabled={!batchId||!token||submitting}>確認烘乾完成</button>:<button type="button" onClick={()=>void submit("/api/operations/start-drying")} disabled={!batchId||!token||submitting}>確認開始烘乾</button>}</ScanStage>{failed?<p className={styles.errorNotice} role="alert">烘乾控制點未完成：{result?.reasonCode}</p>:result?<p className={styles.successNotice} role="status">{result.status==="completed"?"烘乾已結束，洗衣單目前待取件。":result.status==="awaiting_cart"?"烘乾已結束，洗衣單目前待取件。":"烘乾已開始。"}</p>:null}</div>}
