"use client";

import { useEffect, useMemo, useState } from "react";

import styles from "./prototype.module.css";

type Stage = "待收單" | "待清洗" | "浸泡中" | "清洗中" | "待烘衣" | "烘衣中" | "待取物";
type Order = {
  id: string;
  number: string;
  institution: string;
  cart: string;
  category: string;
  stage: Stage;
  progress: number;
  updated: string;
  pieces: number;
  priority: "一般" | "優先" | "緊急";
  due: string;
  equipment: string;
  operator: string;
};
type Activity = { time: string; label: string; detail: string; tone: "teal" | "amber" | "coral" | "muted" };
type Equipment = { code: string; type: string; status: string; load: string; tone: "ready" | "busy" | "issue" };
type DrawerKind = "notifications" | "suggestions" | "audit" | "equipment" | "organizations" | "procedures" | "help";

const stages: Stage[] = ["待收單", "待清洗", "浸泡中", "清洗中", "待烘衣", "烘衣中", "待取物"];
const stageTone: Record<Stage, string> = { 待收單: "neutral", 待清洗: "blue", 浸泡中: "amber", 清洗中: "teal", 待烘衣: "amber", 烘衣中: "orange", 待取物: "green" };

const initialOrders: Order[] = [
  { id: "1", number: "MAIN-20260811-0012", institution: "晴禾護理之家", cart: "CART-MAIN-01", category: "汙衣", stage: "清洗中", progress: 54, updated: "剛剛", pieces: 42, priority: "優先", due: "10:40", equipment: "WASH-02", operator: "王小明" },
  { id: "2", number: "MAIN-20260811-0011", institution: "安康日照中心", cart: "CART-MAIN-02", category: "圍兜", stage: "待烘衣", progress: 68, updated: "3 分鐘前", pieces: 28, priority: "一般", due: "11:10", equipment: "DRY-01", operator: "林怡君" },
  { id: "3", number: "MAIN-20260811-0010", institution: "晴禾護理之家", cart: "CART-MAIN-03", category: "消毒", stage: "浸泡中", progress: 24, updated: "8 分鐘前", pieces: 36, priority: "緊急", due: "09:50", equipment: "DISINF-01", operator: "王小明" },
  { id: "4", number: "CORP-20260811-0007", institution: "法人示範機構", cart: "CART-CORP-01", category: "汙衣", stage: "待取物", progress: 100, updated: "12 分鐘前", pieces: 31, priority: "一般", due: "已完成", equipment: "CART-CORP-01", operator: "陳志宏" },
  { id: "5", number: "MAIN-20260811-0009", institution: "安康日照中心", cart: "CART-MAIN-04", category: "床單", stage: "待收單", progress: 0, updated: "18 分鐘前", pieces: 24, priority: "一般", due: "12:20", equipment: "—", operator: "待收單" },
  { id: "6", number: "MAIN-20260811-0008", institution: "晴禾護理之家", cart: "CART-MAIN-05", category: "消毒", stage: "烘衣中", progress: 82, updated: "21 分鐘前", pieces: 19, priority: "優先", due: "10:15", equipment: "DRY-02", operator: "王小明" },
];

const initialActivity: Activity[] = [
  { time: "08:42", label: "清洗開始", detail: "MAIN-20260811-0012 · WASH-02", tone: "teal" },
  { time: "08:38", label: "洗衣單已收單", detail: "MAIN-20260811-0011 · 安康日照中心", tone: "muted" },
  { time: "08:31", label: "設備異常提醒", detail: "DRY-03 溫度偏高，已標記檢查", tone: "coral" },
  { time: "08:25", label: "洗衣單待取物", detail: "CORP-20260811-0007 · 通知已排入", tone: "amber" },
];

const initialEquipment: Equipment[] = [
  { code: "WASH-01", type: "洗衣機", status: "可用", load: "0 / 1", tone: "ready" },
  { code: "WASH-02", type: "洗衣機", status: "清洗中", load: "1 / 1", tone: "busy" },
  { code: "DRY-01", type: "烘衣機", status: "可用", load: "0 / 1", tone: "ready" },
  { code: "DRY-02", type: "烘衣機", status: "烘衣中", load: "1 / 1", tone: "busy" },
  { code: "DRY-03", type: "烘衣機", status: "需檢查", load: "—", tone: "issue" },
];

const variants = [
  { key: "A", name: "營運總覽" },
  { key: "B", name: "班別看板" },
  { key: "C", name: "掃碼工作台" },
] as const;
type VariantKey = (typeof variants)[number]["key"];

function currentVariant(): VariantKey {
  if (typeof window === "undefined") return "A";
  const value = new URLSearchParams(window.location.search).get("variant");
  return variants.find((variant) => variant.key === value)?.key ?? "A";
}

function Badge({ stage }: { stage: Stage }) { return <span className={`${styles.badge} ${styles[stageTone[stage]]}`}>{stage}</span>; }
function Priority({ priority }: { priority: Order["priority"] }) { return <span className={`${styles.priority} ${priority === "緊急" ? styles.priorityUrgent : priority === "優先" ? styles.priorityHigh : ""}`}>{priority}</span>; }
function Progress({ value }: { value: number }) { return <div className={styles.progress} aria-label={`完成 ${value}%`}><span style={{ width: `${value}%` }} /></div>; }

function PrototypeSwitcher({ current }: { current: string }) {
  const index = Math.max(0, variants.findIndex((variant) => variant.key === current));
  const move = (offset: number) => {
    const next = variants[(index + offset + variants.length) % variants.length].key;
    const url = new URL(window.location.href); url.searchParams.set("variant", next); window.history.replaceState({}, "", url); window.dispatchEvent(new PopStateEvent("popstate"));
  };
  return <nav className={styles.switcher} aria-label="Prototype 版型切換"><button type="button" aria-label="上一個版型" onClick={() => move(-1)}>←</button><span><small>DESIGN STUDY</small><strong>{variants[index].key} · {variants[index].name}</strong></span><button type="button" aria-label="下一個版型" onClick={() => move(1)}>→</button></nav>;
}

export function LaundryPrototype() {
  const [variant, setVariant] = useState<VariantKey>("A");
  const [orders, setOrders] = useState(initialOrders);
  const [selectedId, setSelectedId] = useState("1");
  const [filter, setFilter] = useState<"全部" | Stage | "需注意">("全部");
  const [query, setQuery] = useState("");
  const [toast, setToast] = useState("本地 prototype：所有動作只保留在目前瀏覽器分頁。");
  const [activity, setActivity] = useState(initialActivity);
  const [equipmentState, setEquipmentState] = useState(initialEquipment);
  const [drawer, setDrawer] = useState<DrawerKind | null>(null);
  const selected = orders.find((order) => order.id === selectedId) ?? orders[0];
  const filteredOrders = useMemo(() => orders.filter((order) => { const matchesFilter = filter === "全部" || (filter === "需注意" ? order.priority === "緊急" || order.stage === "烘衣中" : order.stage === filter); const matchesSearch = `${order.number} ${order.institution} ${order.cart} ${order.category}`.toLowerCase().includes(query.toLowerCase()); return matchesFilter && matchesSearch; }), [filter, orders, query]);
  const counts = useMemo(() => stages.reduce<Record<string, number>>((result, stage) => { result[stage] = orders.filter((order) => order.stage === stage).length; return result; }, {}), [orders]);

  useEffect(() => {
    const sync = () => setVariant(currentVariant());
    const keydown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target?.matches("input, textarea, select, [contenteditable=true]")) return; if (event.key === "ArrowLeft") document.querySelector<HTMLButtonElement>('[aria-label="上一個版型"]')?.click(); if (event.key === "ArrowRight") document.querySelector<HTMLButtonElement>('[aria-label="下一個版型"]')?.click(); };
    sync();
    window.addEventListener("popstate", sync); window.addEventListener("keydown", keydown); return () => { window.removeEventListener("popstate", sync); window.removeEventListener("keydown", keydown); };
  }, []);

  const openDrawer = (kind: DrawerKind) => setDrawer(kind);
  const closeDrawer = () => setDrawer(null);
  const selectOrder = (key: string) => { const target = orders.find((order) => order.id === key || order.number === key); if (!target) return; setSelectedId(target.id); closeDrawer(); setToast(`已切換至 ${target.number}。`); };
  const nextStageFor = (order: Order): Stage | null => {
    if (order.stage === "待清洗" && order.category !== "消毒") return "清洗中";
    const index = stages.indexOf(order.stage);
    return index >= stages.length - 1 ? null : stages[index + 1];
  };
  const advanceSelected = () => {
    const nextStage = nextStageFor(selected);
    if (!nextStage) { setToast(`${selected.number} 已完成最後必要階段，等待取件。`); openDrawer("notifications"); return; }
    const equipmentForStage = nextStage === "浸泡中" ? "DISINF-01" : nextStage === "清洗中" ? "WASH-01" : nextStage === "烘衣中" ? "DRY-01" : nextStage === "待取物" ? selected.cart : selected.equipment;
    setOrders((current) => current.map((order) => order.id === selected.id ? { ...order, stage: nextStage, progress: Math.min(100, Math.max(order.progress + (nextStage === "浸泡中" ? 12 : 17), 24)), updated: "剛剛", equipment: equipmentForStage, operator: "王小明" } : order));
    setActivity((current) => [{ time: "剛剛", label: `控制點更新 · ${nextStage}`, detail: `${selected.number} · ${equipmentForStage}`, tone: "teal" as const }, ...current].slice(0, 8));
    setToast(`${selected.number} 已模擬更新為「${nextStage}」。`);
  };
  const reportIssue = () => { setActivity((current) => [{ time: "剛剛", label: "已建立異常草稿", detail: `${selected.number} · 待主管確認`, tone: "coral" as const }, ...current].slice(0, 8)); setToast(`已建立 ${selected.number} 的異常記錄草稿。`); openDrawer("notifications"); };
  const updateEquipment = (code: string, status: Equipment["status"], tone: Equipment["tone"]) => { setEquipmentState((current) => current.map((item) => item.code === code ? { ...item, status, tone, load: status === "可用" ? "0 / 1" : item.load } : item)); setToast(`${code} 已更新為「${status}」。`); };
  const reset = () => { setOrders(initialOrders); setActivity(initialActivity); setEquipmentState(initialEquipment); setSelectedId("1"); setFilter("全部"); setQuery(""); setDrawer(null); setToast("已重設本地 prototype 狀態。"); };

  return <main className={styles.page}>
    <header className={styles.topbar}><div className={styles.brand}><span className={styles.brandMark}>洗</span><div><strong>洗衣房作業台</strong><small>WASH ROOM / OPERATIONS OS</small></div></div><div className={styles.context}><span className={styles.contextLabel}>作業據點</span><strong>MAIN · 本館</strong><span className={styles.contextDivider} /> <span>早班 08:00—16:00</span></div><div className={styles.topActions}><span className={styles.live}><i />資料模擬中</span><button type="button" onClick={reset}>重設</button><button type="button" className={styles.userChip} onClick={() => openDrawer("help")} aria-label="開啟操作說明">王</button></div></header>
    <div className={styles.frame}><aside className={styles.rail}><div className={styles.railSection}><span className={styles.railLabel}>WORKSPACE</span><button type="button" className={styles.railActive} onClick={() => { setFilter("全部"); window.scrollTo({ top: 0, behavior: "smooth" }); }}><span>◈</span>營運總覽</button><button type="button" onClick={() => { setFilter("全部"); document.getElementById("orders")?.scrollIntoView({ behavior: "smooth" }); }}><span>▤</span>洗衣單</button><button type="button" onClick={() => openDrawer("equipment")}><span>◌</span>設備狀態</button><button type="button" onClick={() => openDrawer("notifications")}><span>!</span>異常與通知<em>2</em></button></div><div className={styles.railSection}><span className={styles.railLabel}>ADMIN</span><button type="button" onClick={() => openDrawer("organizations")}><span>⌂</span>送洗機構</button><button type="button" onClick={() => openDrawer("procedures")}><span>◫</span>程序範本</button></div><button type="button" className={styles.railFooter} onClick={() => openDrawer("help")}><span className={styles.helpDot}>?</span><span>需要協助？<small>查看操作說明</small></span></button></aside><div className={styles.main}><div className={styles.pageHeader}><div><p className={styles.overline}>TUESDAY · AUG 11, 2026</p><h1>{variant === "C" ? "掃描、確認、繼續。" : "早安，王小明。"}</h1><p className={styles.subtitle}>{variant === "C" ? "每一次掃碼都是一個可追蹤的控制點。" : "今天有 6 張洗衣單正在你的作業範圍內。"}</p></div><div className={styles.headerTools}><label className={styles.search}><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋洗衣單、機構或洗衣車" /></label><button type="button" className={styles.iconButton} onClick={() => openDrawer("notifications")} aria-label="開啟通知中心">♢<b>2</b></button></div></div><div className={styles.notice}><span>✦</span><strong>{toast}</strong><button type="button" onClick={() => openDrawer("suggestions")}>查看建議 →</button></div>{variant === "A" ? <Overview orders={filteredOrders} allOrders={orders} counts={counts} filter={filter} setFilter={setFilter} selected={selected} selectedId={selectedId} setSelectedId={setSelectedId} advance={advanceSelected} reportIssue={reportIssue} activity={activity} equipment={equipmentState} openDrawer={openDrawer} selectOrder={selectOrder} /> : null}{variant === "B" ? <Board orders={orders} counts={counts} selected={selected} selectedId={selectedId} setSelectedId={setSelectedId} advance={advanceSelected} openDrawer={openDrawer} /> : null}{variant === "C" ? <Operator orders={orders} selected={selected} selectedId={selectedId} setSelectedId={setSelectedId} advance={advanceSelected} reportIssue={reportIssue} openDrawer={openDrawer} /> : null}</div></div><PrototypeDrawer kind={drawer} selected={selected} orders={orders} activity={activity} equipment={equipmentState} onClose={closeDrawer} onSelectOrder={selectOrder} onAdvance={advanceSelected} onReportIssue={reportIssue} onEquipmentUpdate={updateEquipment} onToast={setToast} />
    {process.env.NODE_ENV !== "production" ? <PrototypeSwitcher current={variant} /> : null}
  </main>;
}

type OverviewProps = { orders: Order[]; allOrders: Order[]; counts: Record<string, number>; filter: "全部" | Stage | "需注意"; setFilter: (filter: "全部" | Stage | "需注意") => void; selected: Order; selectedId: string; setSelectedId: (id: string) => void; advance: () => void; reportIssue: () => void; activity: Activity[]; equipment: Equipment[]; openDrawer: (kind: DrawerKind) => void; selectOrder: (id: string) => void };
function Overview({ orders, allOrders, counts, filter, setFilter, selected, selectedId, setSelectedId, advance, reportIssue, activity, equipment, openDrawer, selectOrder }: OverviewProps) {
  return <><section className={styles.summary}><div className={styles.summaryLead}><div><span className={styles.sectionTag}>TODAY AT A GLANCE</span><h2>流程進度比昨天更快 <mark>6%</mark></h2><p>目前有 {counts["清洗中"] + counts["烘衣中"]} 台設備運轉中。預估今日 14:30 前完成所有必要批次。</p></div><div className={styles.summaryFigure}><strong>78</strong><span>%</span><small>今日完成率</small></div></div><div className={styles.metrics}><Metric label="待收單" value={counts["待收單"]} sub="送洗員尚未送達" tone="sand" /><Metric label="待清洗" value={counts["待清洗"]} sub="等待洗衣機" tone="sky" /><Metric label="設備運轉" value={counts["清洗中"] + counts["烘衣中"]} sub="清洗與烘衣" tone="mint" /><Metric label="待取物" value={counts["待取物"]} sub="可通知取件" tone="peach" /></div></section><section className={styles.contentGrid}><div className={styles.queuePanel} id="orders"><div className={styles.sectionHeader}><div><span className={styles.sectionTag}>LIVE QUEUE / {allOrders.length}</span><h2>洗衣單流程</h2></div><span className={styles.queueHint}>最後更新：剛剛</span></div><div className={styles.filterRow}>{["全部", "待收單", "待清洗", "浸泡中", "清洗中", "待烘衣", "烘衣中", "待取物", "需注意"].map((item) => <button type="button" className={filter === item ? styles.filterActive : ""} onClick={() => setFilter(item as OverviewProps["filter"])} key={item}>{item}{item !== "全部" && item !== "需注意" ? <b>{counts[item] ?? 0}</b> : null}</button>)}</div><div className={styles.tableHead}><span>洗衣單 / 機構</span><span>階段</span><span>優先</span><span>預計</span><span /></div><div className={styles.orderList}>{orders.map((order) => <button type="button" className={`${styles.orderItem} ${selectedId === order.id ? styles.orderItemSelected : ""}`} key={order.id} onClick={() => setSelectedId(order.id)}><span className={styles.orderIdentity}><strong>{order.number}</strong><small>{order.institution} · {order.category} · {order.pieces} 件</small></span><Badge stage={order.stage} /><Priority priority={order.priority} /><span className={styles.due}>{order.due}</span><span className={styles.chevron}>›</span></button>)}</div>{orders.length === 0 ? <div className={styles.empty}>找不到符合條件的洗衣單。</div> : null}</div><Inspector order={selected} advance={advance} reportIssue={reportIssue} onOpenAudit={() => openDrawer("audit")} /></section><section className={styles.bottomGrid}><ActivityPanel activity={activity} onOpenAudit={() => openDrawer("audit")} onSelectOrder={selectOrder} /><EquipmentPanel equipment={equipment} onOpenEquipment={() => openDrawer("equipment")} /></section></>;
}
function Metric({ label, value, sub, tone }: { label: string; value: number; sub: string; tone: string }) { return <article className={`${styles.metric} ${styles[tone]}`}><span>{label}</span><strong>{value}</strong><small>{sub}</small></article>; }
function Inspector({ order, advance, reportIssue, onOpenAudit }: { order: Order; advance: () => void; reportIssue: () => void; onOpenAudit: () => void }) { return <aside className={styles.inspector}><div className={styles.inspectorHead}><div><span className={styles.sectionTag}>SELECTED ORDER</span><h2>{order.number}</h2></div><Priority priority={order.priority} /></div><p className={styles.institution}>{order.institution} <span>·</span> {order.category}</p><div className={styles.inspectorStats}><span>件數<strong>{order.pieces}</strong></span><span>預計完成<strong>{order.due}</strong></span><span>目前設備<strong>{order.equipment}</strong></span></div><div className={styles.stagePath}>{stages.map((stage, index) => { const active = stages.indexOf(order.stage) >= index; return <div className={`${styles.pathItem} ${active ? styles.pathActive : ""}`} key={stage}><i>{active ? "✓" : index + 1}</i><span>{stage}<small>{active ? (stage === order.stage ? "現在" : "完成") : "等待"}</small></span></div>; })}</div><div className={styles.inspectorProgress}><div><span>流程完成度</span><strong>{order.progress}%</strong></div><Progress value={order.progress} /></div><div className={styles.inspectorActions}><button type="button" className={styles.primary} onClick={advance}>推進下一控制點 <span>↗</span></button><button type="button" className={styles.secondary} onClick={reportIssue}>回報異常</button></div><button type="button" className={styles.auditLine} onClick={onOpenAudit}>查看這張洗衣單的完整稽核 →</button></aside>; }
function ActivityPanel({ activity, onOpenAudit, onSelectOrder }: { activity: Activity[]; onOpenAudit: () => void; onSelectOrder: (id: string) => void }) { return <section className={styles.activityPanel}><div className={styles.sectionHeader}><div><span className={styles.sectionTag}>AUDIT TRAIL</span><h2>最近活動</h2></div><button type="button" className={styles.inlineLink} onClick={onOpenAudit}>完整稽核 →</button></div><div className={styles.activityList}>{activity.map((item, index) => <button type="button" className={styles.activityItem} key={`${item.time}-${index}`} onClick={() => { const match = item.detail.match(/[A-Z]+-\d{8}-\d{4}/); if (match) onSelectOrder(match[0]); else onOpenAudit(); }}><i className={styles[item.tone]} /><time>{item.time}</time><span><strong>{item.label}</strong><small>{item.detail}</small></span></button>)}</div></section>; }
function EquipmentPanel({ equipment, onOpenEquipment }: { equipment: Equipment[]; onOpenEquipment: () => void }) { return <section className={styles.equipmentPanel} id="equipment"><div className={styles.sectionHeader}><div><span className={styles.sectionTag}>EQUIPMENT / {String(equipment.length).padStart(2, "0")}</span><h2>設備狀態</h2></div><button type="button" className={styles.inlineLink} onClick={onOpenEquipment}>管理設備 →</button></div><div className={styles.equipmentList}>{equipment.map((item) => <button type="button" className={styles.equipmentItem} key={item.code} onClick={onOpenEquipment}><i className={styles[`equipment_${item.tone}`]} /><span><strong>{item.code}</strong><small>{item.type} · {item.load}</small></span><em className={styles[`equipmentText_${item.tone}`]}>{item.status}</em></button>)}</div></section>; }

type BoardProps = { orders: Order[]; counts: Record<string, number>; selected: Order; selectedId: string; setSelectedId: (id: string) => void; advance: () => void; openDrawer: (kind: DrawerKind) => void };
function Board({ orders, counts, selected, selectedId, setSelectedId, advance, openDrawer }: BoardProps) { const columns: Stage[] = stages; const nextLabel = selected.stage === "待取物" ? "等待匿名取件" : `掃描${selected.stage === "待清洗" && selected.category !== "消毒" ? "清洗中" : stages[Math.min(stages.length - 1, stages.indexOf(selected.stage) + 1)]}控制點`; return <section className={styles.boardLayout}><div className={styles.boardMain}><div className={styles.boardTitle}><div><span className={styles.sectionTag}>SHIFT BOARD / MORNING</span><h2>今天的控制點</h2><p>每張洗衣單都能從看板進入詳情、模擬掃碼並回到稽核軌跡。</p></div><div className={styles.boardStats}><button type="button" onClick={() => openDrawer("notifications")}><strong>{orders.length}</strong> 張洗衣單</button><button type="button" onClick={() => openDrawer("equipment")}><strong>{counts["清洗中"] + counts["烘衣中"]}</strong> 運轉中</button></div></div><div className={styles.kanban}>{columns.map((stage) => <div className={styles.column} key={stage}><div className={styles.columnHead}><span>{stage}</span><b>{counts[stage] ?? 0}</b></div>{orders.filter((order) => order.stage === stage).map((order) => <button type="button" className={`${styles.task} ${selectedId === order.id ? styles.taskSelected : ""}`} key={order.id} onClick={() => setSelectedId(order.id)}><div className={styles.taskTop}><strong>{order.number.split("-").slice(-1)[0]}</strong><Priority priority={order.priority} /></div><span>{order.institution}</span><small>{order.category} · {order.pieces} 件</small><Progress value={order.progress} /><em>{order.equipment === "—" ? "等待設備" : order.equipment}</em></button>)}</div>)}</div></div><aside className={styles.brief}><span className={styles.sectionTag}>SELECTED</span><h2>{selected.number}</h2><p>{selected.institution} · {selected.category}</p><div className={styles.briefStage}><Badge stage={selected.stage} /><strong>{selected.progress}%</strong></div><Progress value={selected.progress} /><dl><div><dt>下一步</dt><dd>{nextLabel}</dd></div><div><dt>操作者</dt><dd>{selected.operator}</dd></div><div><dt>預計完成</dt><dd>{selected.due}</dd></div></dl><button type="button" className={styles.primary} onClick={advance}>模擬掃碼並推進</button><button type="button" className={styles.secondary} onClick={() => openDrawer("audit")}>查看批次稽核</button><p className={styles.briefNote}>狀態更新會同步寫入批次歷程與稽核軌跡。</p></aside></section>; }

type OperatorProps = { orders: Order[]; selected: Order; selectedId: string; setSelectedId: (id: string) => void; advance: () => void; reportIssue: () => void; openDrawer: (kind: DrawerKind) => void };
function Operator({ orders, selected, selectedId, setSelectedId, advance, reportIssue, openDrawer }: OperatorProps) { const nextLabel = selected.stage === "待取物" ? "這張洗衣單已完成" : `掃描${selected.stage === "待清洗" && selected.category !== "消毒" ? "清洗中" : stages[Math.min(stages.length - 1, stages.indexOf(selected.stage) + 1)]}設備 QR`; return <section className={styles.operatorLayout}><div className={styles.operatorMain}><div className={styles.operatorGreeting}><div><span className={styles.sectionTag}>OPERATOR MODE / CONTROL POINT</span><h2>掃描，確認，繼續。</h2><p>洗衣員 王小明 · MAIN 本館 · 早班進行中</p></div><button type="button" className={styles.workerAvatar} onClick={() => openDrawer("help")} aria-label="開啟操作說明">王</button></div><div className={styles.scanStage}><div className={styles.scanVisual}><div className={styles.scanCorners}><i /><i /><i /><i /></div><div className={styles.scanGlyph}>▦</div><span className={styles.scanBeam} /></div><div className={styles.scanCopy}><span className={styles.scanReady}>● READY TO SCAN</span><h3>{nextLabel}</h3><p>{selected.number}<br />{selected.cart} · {selected.category} · {selected.pieces} 件</p><button type="button" className={styles.scanButton} onClick={advance}>模擬掃描 {selected.equipment === "—" ? selected.cart : selected.equipment} <span>↗</span></button></div></div><div className={styles.operatorActions}><button type="button" onClick={advance}><span>↗</span><strong>完成目前階段</strong><small>更新批次狀態</small></button><button type="button" onClick={reportIssue}><span>!</span><strong>回報異常</strong><small>設備／衣物／程序</small></button><button type="button" onClick={() => setSelectedId(orders[(orders.findIndex((order) => order.id === selected.id) + 1) % orders.length].id)}><span>↔</span><strong>切換批次</strong><small>查看我的待辦</small></button><button type="button" onClick={() => openDrawer("audit")}><span>☷</span><strong>查看稽核</strong><small>確認這張單的歷程</small></button></div></div><aside className={styles.operatorQueue}><div className={styles.queueHeader}><div><span className={styles.sectionTag}>MY QUEUE / {orders.length}</span><h2>我的待辦</h2></div><button type="button" className={styles.queueClock} onClick={() => openDrawer("notifications")}>08:42 · 2 則提醒</button></div>{orders.map((order) => <button type="button" key={order.id} className={`${styles.queueItem} ${order.id === selectedId ? styles.queueItemActive : ""}`} onClick={() => setSelectedId(order.id)}><span className={styles.queueIndicator}>{order.id === selectedId ? "●" : "○"}</span><span><strong>{order.number}</strong><small>{order.category} · {order.stage}</small></span><Badge stage={order.stage} /></button>)}</aside></section>; }

function PrototypeDrawer({ kind, selected, orders, activity, equipment, onClose, onSelectOrder, onAdvance, onReportIssue, onEquipmentUpdate, onToast }: { kind: DrawerKind | null; selected: Order; orders: Order[]; activity: Activity[]; equipment: Equipment[]; onClose: () => void; onSelectOrder: (key: string) => void; onAdvance: () => void; onReportIssue: () => void; onEquipmentUpdate: (code: string, status: Equipment["status"], tone: Equipment["tone"]) => void; onToast: (message: string) => void }) {
  if (!kind) return null;
  const urgent = orders.find((order) => order.priority === "緊急");
  const title: Record<DrawerKind, string> = { notifications: "通知與異常", suggestions: "今日建議", audit: "完整稽核軌跡", equipment: "設備管理", organizations: "送洗機構", procedures: "程序範本", help: "操作說明" };
  const eyebrow: Record<DrawerKind, string> = { notifications: "NOTIFICATIONS / 02", suggestions: "NEXT BEST ACTION", audit: `AUDIT TRAIL / ${activity.length}`, equipment: `EQUIPMENT / ${equipment.length}`, organizations: "INSTITUTIONS / MAIN", procedures: "PROCEDURES / ACTIVE", help: "QUICK GUIDE / LOCAL PROTOTYPE" };
  return <div className={styles.drawerBackdrop} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="prototype-drawer-title"><header className={styles.drawerHeader}><div><span className={styles.sectionTag}>{eyebrow[kind]}</span><h2 id="prototype-drawer-title">{title[kind]}</h2></div><button type="button" className={styles.drawerClose} onClick={onClose} aria-label="關閉">×</button></header><div className={styles.drawerBody}>
    {kind === "notifications" ? <><p className={styles.drawerIntro}>這些提醒會跟著洗衣單狀態與設備事件更新，點擊即可回到對應控制點。</p><div className={styles.drawerList}>{activity.filter((item) => item.tone === "coral" || item.tone === "amber").map((item, index) => <button type="button" className={styles.drawerRow} key={`${item.time}-${index}`} onClick={() => { const match = item.detail.match(/[A-Z]+-\d{8}-\d{4}/); if (match) onSelectOrder(match[0]); else onClose(); }}><span className={`${styles.drawerDot} ${styles[item.tone]}`} /><span><strong>{item.label}</strong><small>{item.detail}</small></span><b>›</b></button>)}</div><div className={styles.drawerActions}>{urgent ? <button type="button" className={styles.primary} onClick={() => onSelectOrder(urgent.number)}>處理緊急批次 · {urgent.number.slice(-4)}</button> : null}<button type="button" className={styles.secondary} onClick={onReportIssue}>建立目前批次異常</button></div></> : null}
    {kind === "suggestions" ? <><p className={styles.drawerIntro}>按照目前的優先級、設備負載與預計完成時間，建議依序處理：</p><ol className={styles.suggestionList}><li><strong>先處理緊急消毒批次</strong><span>{urgent?.number ?? "目前沒有緊急批次"} · 需完成浸泡後再清洗</span></li><li><strong>釋放 DRY-03 檢查標記</strong><span>避免下一張待烘衣洗衣單卡在等待設備</span></li><li><strong>通知已完成批次取件</strong><span>CORP-20260811-0007 已在待取物</span></li></ol><div className={styles.drawerActions}>{urgent ? <button type="button" className={styles.primary} onClick={() => onSelectOrder(urgent.number)}>開啟緊急批次</button> : null}<button type="button" className={styles.secondary} onClick={() => { onToast("已將今日建議加入早班工作清單。"); onClose(); }}>加入早班工作清單</button></div></> : null}
    {kind === "audit" ? <><p className={styles.drawerIntro}>目前聚焦 {selected.number}。Prototype 以記憶體模擬稽核事件；每次推進、異常與設備變更都會在這裡留下可追蹤紀錄。</p><div className={styles.drawerList}>{activity.map((item, index) => <button type="button" className={styles.drawerRow} key={`${item.time}-${index}`} onClick={() => { const match = item.detail.match(/[A-Z]+-\d{8}-\d{4}/); if (match) onSelectOrder(match[0]); }}><time>{item.time}</time><span><strong>{item.label}</strong><small>{item.detail}</small></span><b>›</b></button>)}</div><div className={styles.drawerActions}><button type="button" className={styles.primary} onClick={onAdvance}>推進目前批次並新增稽核</button><button type="button" className={styles.secondary} onClick={onClose}>返回作業畫面</button></div></> : null}
    {kind === "equipment" ? <><p className={styles.drawerIntro}>點擊設備可以模擬釋放、標記異常與恢復可用，狀態會同步回總覽與工作台。</p><div className={styles.drawerList}>{equipment.map((item) => <div className={styles.drawerRow} key={item.code}><i className={styles[`equipment_${item.tone}`]} /><span><strong>{item.code} · {item.type}</strong><small>{item.status} · 負載 {item.load}</small></span><button type="button" className={styles.drawerMiniButton} onClick={() => onEquipmentUpdate(item.code, item.status === "可用" ? "需檢查" : "可用", item.status === "可用" ? "issue" : "ready")}>{item.status === "可用" ? "標記異常" : "釋放設備"}</button></div>)}</div><div className={styles.drawerActions}><button type="button" className={styles.secondary} onClick={() => { onToast("已重新整理設備狀態。"); onClose(); }}>重新整理設備</button></div></> : null}
    {kind === "organizations" ? <><p className={styles.drawerIntro}>依機構查看目前洗衣單；選取後會回到總覽並聚焦該筆批次。</p><div className={styles.drawerList}>{Array.from(new Set(orders.map((order) => order.institution))).map((institution) => { const first = orders.find((order) => order.institution === institution)!; const count = orders.filter((order) => order.institution === institution).length; return <button type="button" className={styles.drawerRow} key={institution} onClick={() => onSelectOrder(first.number)}><span><strong>{institution}</strong><small>{count} 張洗衣單 · 最近 {first.stage}</small></span><b>›</b></button>; })}</div><div className={styles.drawerActions}><button type="button" className={styles.secondary} onClick={() => { onToast("機構主檔 prototype 操作已開啟，正式版會連結管理頁。"); onClose(); }}>新增送洗機構</button></div></> : null}
    {kind === "procedures" ? <><p className={styles.drawerIntro}>程序範本會決定每個控制點的順序與預估時間；這裡先模擬主管套用規則。</p><div className={styles.procedureSteps}>{stages.map((stage, index) => <div key={stage}><b>{String(index + 1).padStart(2, "0")}</b><span>{stage}</span><small>{stage === "浸泡中" ? "消毒分類才啟用" : index === 0 ? "送洗員控制點" : "洗衣員控制點"}</small></div>)}</div><div className={styles.drawerActions}><button type="button" className={styles.primary} onClick={() => { onToast("已套用「消毒＋洗烘」程序範本到本地 prototype。"); onClose(); }}>套用消毒＋洗烘範本</button><button type="button" className={styles.secondary} onClick={() => { onToast("已建立一份自訂程序草稿。"); onClose(); }}>建立自訂程序草稿</button></div></> : null}
    {kind === "help" ? <><p className={styles.drawerIntro}>這個 prototype 對應洗衣房的控制點流程，所有動作只在目前分頁模擬。</p><div className={styles.helpList}><div><kbd>←</kbd><kbd>→</kbd><span>切換三種版型</span></div><div><kbd>推進</kbd><span>將選取洗衣單送往下一控制點</span></div><div><kbd>掃碼</kbd><span>模擬設備 QR Code 驗證並寫入稽核</span></div><div><kbd>異常</kbd><span>建立異常草稿並送到通知中心</span></div></div><div className={styles.drawerActions}><button type="button" className={styles.primary} onClick={() => { onToast("已完成快速導覽，現在可以開始操作。"); onClose(); }}>開始操作</button></div></> : null}
  </div></section></div>;
}
